Added new perspectives
PicPay/picpay-desafio-backend pull request #27
Opened 2020-08-10 12:30 UTC by vinyvicente

2020-08-10 12:33 UTC, josemiguelq commented on readme.md
> +Caso você **não se sinta à vontade** com a arquitetura proposta, você pode apresentar sua solução utilizando frameworks diferentes.
```suggestion
Apresente sua solução utilizando no frameworks que você desejar justificando a escolha.
```

2020-08-10 12:33 UTC, josemiguelq commented on readme.md
> +* Síntaxe de PHP impecável
```suggestion
* Síntaxe de PHP
```

2020-08-10 12:33 UTC, josemiguelq commented on readme.md
> +* Unit tests
```suggestion
* Teste unitários
```

2020-08-10 12:45 UTC, joubertredrat commented on readme.md
> +Apresente sua solução utilizando no frameworks que você desejar justificando a escolha.
Acho que assim fica melhor. "Apresente sua solução utilizando o framework que você desejar, justificando a escolha"

2020-08-10 12:46 UTC, lucianocarvalho commented on readme.md
> +  * Entrevista com o TechManager
```suggestion
  * Entrevista com o Tech Manager
```

2020-08-10 12:46 UTC, lucianocarvalho commented on readme.md
> +* Síntaxe de PHP impecável
RT

2020-08-10 12:47 UTC, lucianocarvalho commented on readme.md
> +* Cleancode
```suggestion
* Clean code
```

2020-08-10 12:47 UTC, lucianocarvalho approved these changes

2020-08-10 12:48 UTC, joubertredrat commented on readme.md
> +* Evitar side effect (concorrência)
Talvez considerar "Evitar side effect ou race condition (concorrência)"

2020-08-10 13:10 UTC, joubertredrat requested changes

2020-08-10 13:10 UTC, joubertredrat commented on readme.md
> +Apresente sua solução utilizando no frameworks que você desejar justificando a escolha.
Apresente sua solução utilizando o framework que você desejar, justificando a escolha.

2020-08-10 13:10 UTC, joubertredrat commented on readme.md
> +- Frontend (só avaliaremos a API Restful)
Frontend, só será avaliado os endpoints API Restful

2020-08-10 13:10 UTC, joubertredrat commented on readme.md
> +* Evitar side effect (concorrência)
Evitar side effect ou race condition (concorrência)

2020-08-10 13:47 UTC, josemiguelq approved these changes

2020-08-10 13:49 UTC, ruschoni02 approved these changes

2020-08-10 13:49 UTC, ruschoni02 commented on readme.md
> +* Teste unitários
Unit test, acho que poderia estar em Pleno, pois um pleno já deveria conhecer e aplicar no dia a dia

2020-08-10 18:27 UTC, lucianocarvalho commented on readme.md
> +* **Nos surpreenda!**
Eu deixaria os temas mais abrangentes, deixando a aplicação livre pro candidato.

```suggestion
O que avaliamos e gostariamos que, se você se sentir confortável, aplicasse:

* Ótimo raciocínio lógico e se conseguir argumentar suas escolhas
* Conhecimento sobre design patterns
* PSRs
* Modelagem de bancos relacionais e não relacionais
* Desacoplamento de componentes (mais camadas, repository, service, etc)
* Código limpo (sintaxe, clean code, variáveis e afins).
* Fluxos assíncronos
* Evitar side effect ou race condition (concorrência)
* Autonomia (_trick - você pode definir a arquitetura do seu transfer, como também definir um endpoint de acordo com o desafio da melhor forma_)
```

2020-08-10 18:27 UTC, lucianocarvalho approved these changes

2020-08-14 16:17 UTC, josemiguelq commented on readme.md
> +* **Nos surpreenda!**
O que olhamos com atenção:
- Variedade de testes (unitários, integração, api)
- Um código limpo e legível (nomenclatura, etc)
- Conhecimento de padrões (PSRs, design patterns, SOLID)
- Saber argumentar suas escolhas
- Carinho em desacoplar componentes (outras camadas, service, repository)

2020-08-14 17:07 UTC, josemiguelq commented on readme.md
> +  * Sua proposta!
```suggestion
```

2020-08-14 17:50 UTC, jp-ataide approved these changes

2020-08-14 18:30 UTC, merged